# Framework 16 "scope" - Main machine configuration
# AMD Ryzen 7 7840HS + Radeon 780M (iGPU) + Radeon RX 7700S (dGPU)
{
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [
    # Disk partitioning (disko)
    ./disko-scope.nix

    # Modular NixOS configurations
    ./nixos-modules/desktop.nix
    ./nixos-modules/power.nix
    ./nixos-modules/nix-settings.nix
    ./nixos-modules/user.nix
    ./nixos-modules/ssh.nix
    ./nixos-modules/tailscale.nix

    # GitOps auto-deployment (depot pattern)
    ./nixos-modules/depot-sync.nix
    ./nixos-modules/depot-deploy-machine.nix
    ./nixos-modules/depot-deploy-home.nix

    # WiFi networks
    ./nixos-modules/wifi.nix
  ];

  # ============================================================
  # Machine Identity
  # ============================================================

  networking.hostName = "scope";
  networking.networkmanager.enable = true;

  # ============================================================
  # Boot Configuration
  # ============================================================

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Latest kernel for best Framework 16 support
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Framework 16 kernel modules
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "amdgpu" # Early KMS for smooth boot
  ];
  boot.kernelModules = ["kvm-amd" "amdgpu"];

  # AMD-specific kernel parameters
  boot.kernelParams = [
    # Display color accuracy (disable Active Backlight Management)
    "amdgpu.abmlevel=0"

    # Better sleep on AMD
    "mem_sleep_default=s2idle"

    # Sleep/wake fixes
    "amdgpu.dcdebugmask=0x10"

    # dGPU power management
    "amdgpu.runpm=1"
    "amdgpu.aspm=1"
  ];

  # ============================================================
  # Filesystem Configuration
  # ============================================================
  # NOTE: fileSystems and swapDevices are auto-generated by disko
  # from disko-scope.nix - do NOT define them manually here!

  # ============================================================
  # Secrets Management (sops-nix)
  # ============================================================

  sops.defaultSopsFormat = "yaml";
  sops.defaultSopsFile = ../secrets/scope.yaml;
  sops.age.sshKeyPaths = ["/etc/ssh/ssh_host_ed25519_key"];

  # ============================================================
  # Platform
  # ============================================================

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # NixOS release version
  system.stateVersion = "25.05";
}
